settings:
  log_level: root
variables:
  prompt:
    prompt_templates:
      simple: Given the following text, classify it into _insert bias detail_. Consider if the article is biased towards one side or the other and if the text has a particular political leaning. Your response should only be a single word for which side the text leans towards _insert bias detail_
    bias_details:
      binary: biased or nonbiased
      multiclass: center, left or right
    responses:
      binary: Return only 'biased' or 'nonbiased',
      multiclass: Return only 'center', 'left' or 'right'
    roles: ["News article writer","Media bias researcher", "Media bias data annotator"]
experiment_setup:
  conversions:
    prompt_type:
      simple: s
      role: r
      complex: c
    text_type:
      article: a
      sentence: s
    response_type:
      none: n
      writer: w
      researcher: r
      annotator: a
